version: '3'
services:
  ms-sms-sender-sandbox:
    container_name: ms-sms-sender-sandbox
    image: 'ms-sms-sender:latest'
    restart: always
    depends_on:
      - ms-sms-sender-sandbox-wiremock
    links:
      - ms-sms-sender-sandbox-wiremock:wiremock
    ports:
      - '9031:8080'
    environment:
      - JAVA_OPTS=-server -Dfile.encoding=UTF-8 -Xms128m -Xmx256m
      - SPRING_PROFILES_ACTIVE=sandbox
      - SMS_PROVIDER=linkmobility
      - INTEGRATION_TELIA_API_URL=http://wiremock:8080/telia/sms
      - INTEGRATION_TELIA_TOKEN_URL=http://wiremock:8080/telia/token
      - INTEGRATION_TELIA_CLIENT_ID=dummy
      - INTEGRATION_TELIA_CLIENT_SECRET=dummy
      - INTEGRATION_LINKMOBILITY_API_URL=http://wiremock:8080/linkmobility
      - INTEGRATION_LINKMOBILITY_USERNAME=dummy
      - INTEGRATION_LINKMOBILITY_PASSWORD=dummy
      - INTEGRATION_LINKMOBILITY_PLATFORM_ID=dummy
      - INTEGRATION_LINKMOBILITY_PLATFORM_PARTNER_ID=dummy

  ms-sms-sender-sandbox-wiremock:
    container_name: ms-sms-sender-sandbox-wiremock
    image: wiremock/wiremock:2.32.0
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/sandbox/wiremock:/home/wiremock

