version: '3'
services:
  ms-sms-sender-sandbox:
    container_name: ms-sms-sender-sandbox
    image: 'evil.sundsvall.se/ms-sms-sender:latest'
    restart: always
    depends_on:
      - ms-sms-sender-sandbox-wiremock
    links:
      - ms-sms-sender-sandbox-wiremock:wiremock
    ports:
      - '9031:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=sandbox

      # Telia SMS integration
      - PROVIDER_TELIA_BASE_URL=http://wiremock:8080/telia/sms
      - PROVIDER_TELIA_PRIORITY=1
      - PROVIDER_TELIA_ENABLED=true
      - PROVIDER_TELIA_FLASH_CAPABLE=false
      - PROVIDER_TELIA_OAUTH2_TOKEN_URL=http://wiremock:8080/telia/token
      - PROVIDER_TELIA_OAUTH2_CLIENT_ID=someClientId
      - PROVIDER_TELIA_OAUTH2_CLIENT_SECRET=someClientSecret

      # LinkMobility SMS integration
      - PROVIDER_LINKMOBILITY_BASE_URL=http://wiremock:8080/linkmobility
      - PROVIDER_LINKMOBILITY_PRIORITY=2
      - PROVIDER_LINKMOBILITY_ENABLED=true
      - PROVIDER_LINKMOBILITY_FLASH_CAPABLE=true
      - PROVIDER_LINKMOBILITY_BASICAUTH_USERNAME=someUsername
      - PROVIDER_LINKMOBILITY_BASICAUTH_PASSWORD=somePassword
      - PROVIDER_LINKMOBILITY_PLATFORM_ID=somePlatformId
      - PROVIDER_LINKMOBILITY_PLATFORM_PARTNER_ID=somePlatformPartnerId

  ms-sms-sender-sandbox-wiremock:
    container_name: ms-sms-sender-sandbox-wiremock
    image: wiremock/wiremock:2.32.0
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/sandbox/wiremock:/home/wiremock

